steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running git command"
secretEnv: ['GITHUB_TOKEN']

secrets:
  - secretEnv:
      GITHUB_TOKEN: projects/tymestack-439409/secrets/tymestack-github1-github-oauthtoken-39fdc6/versions/latest
