steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/tymestack-439409/tymestack-github/tymestackci','-f', 'main/Dockerfile', 'main']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/tymestack-439409/tymestack-github/tymestackci']

  # Set environment variables for the Kubernetes cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=tymestack-cluster'        # Replace with your cluster name
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'KUBECTL_VERSION=1.30'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'tymestack-cluster'                                   # Replace with your cluster name
      - '--zone=us-central1'                            # Replace with your cluster zone

  # Run the Kubernetes job using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=tymestack-cluster'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'KUBECTL_VERSION=1.30'
    args:
      - 'apply'
      - '-f'
      - 'main/xgboost-job-ci.yaml'





logsBucket: gs://tymestack-bucket
serviceAccount: projects/tymestack-439409/serviceAccounts/33753718603-compute@developer.gserviceaccount.com