apiVersion: batch/v1
kind: Job
metadata:
  name: xgboost-job
spec:
  parallelism: 1  # Number of parallel jobs
  completions: 1  # Number of total jobs
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: xgboost-container
        image: gcr.io/tymestack-439409/tymestack-github
        imagePullPolicy: Always
      restartPolicy: Never
