apiVersion: batch/v1
kind: Job
metadata:
  name: xgboost-job-ci
spec:
  parallelism: 1  # Number of parallel jobs
  completions: 1  # Number of total jobs
  template:
    spec:
      serviceAccountName: ksa
      containers:
      - name: xgboost-container
        image: us-central1-docker.pkg.dev/tymestack-439409/tymestack-github/tymestackci:latest
        imagePullPolicy: Always
      restartPolicy: Never
