apiVersion: batch/v1
kind: Job
metadata:
  name: xgboost-job
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      serviceAccountName: ksa    # kubernetes service account created and then annoted to google service account
      containers:
      - name: xgboost-container
        image: gcr.io/tymestack-439409/tymestack:latest
        imagePullPolicy: Always
      restartPolicy: Never
